apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cpython-
  namespace: argo-wf
spec:
  entrypoint: step-runner
  arguments:
    parameters:
    - name: input_value
      value: "52"
    - name: operation
      value: "nothing"
  templates:
  - name: step-runner
    steps:
      - - name: add
          template: base-step
          arguments:
            parameters:
              - name: operation
                value: "+"
              - name: input_value
                value: "52"
        - name: substract
          template: base-step
          arguments:
            parameters:
              - name: operation
                value: "-"
              - name: input_value
                value: "52"
      - - name: multiply
          template: base-step
          arguments:
            parameters:
              - name: operation
                value: "*"
              - name: input_value
                value: "52"
        - name: divide
          template: base-step
          arguments:
            parameters:
              - name: operation
                value: "/"
              - name: input_value
                value: "52"
      - - name: nada
          template: base-step
          arguments:
            parameters:
              - name: operation
                value: "52"
              - name: input_value
                value: "52"

  - name: base-step
    serviceAccountName: argo-wf-sa
    inputs:
      parameters:
      - name: input_value
      - name: operation
    container:
      image: deceivious/arg_wf
      command:
      - python3
      - "/app/main.py"
      args:
      - "{{inputs.parameters.input_value}}"
      - "{{inputs.parameters.operation}}"
