apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: cpython-
  namespace: argo-wf
spec:
  entrypoint: complete-workflow
  arguments:
    parameters:
    - name: input_value
      value: "52"
    - name: operation
      value: "nothing"
  templates:
  - name: complete-workflow
    steps:
      - - name: extract
          template: extract
          arguments:
            parameters:
              - name: country
                value: "NO"

  - name: extract
    serviceAccountName: argo-wf-sa
    inputs:
      parameters:
      - name: country
    container:
      image: deceivious/arg_wf
      command:
      - python3
      - "/app/extract.py"
      args:
      - "{{inputs.parameters.country}}"


  - name: transform
    serviceAccountName: argo-wf-sa
    inputs:
      parameters:
      - name: regions
    container:
      image: deceivious/arg_wf
      command:
      - python3
      - "/app/transform.py"
      args:
      - "{{inputs.parameters.regions}}"


  - name: load
    serviceAccountName: argo-wf-sa
    inputs:
      parameters:
      - name: region_str
    container:
      image: deceivious/arg_wf
      command:
      - python3
      - "/app/load.py"
      args:
      - "{{inputs.parameters.region_str}}"

